### PR TITLE
Update winscp.sls to ver. 5.7.4

### PR DESCRIPTION
**Pull request by TheBigBear**
Updated winscp.sls to ver. 5.7.4

### CODE REVIEW

**Comment by UtahDave** [comment]
@TheBigBear it looks like this one might be mal-formed. Is that second line correct?

**Comment by TheBigBear** [comment]
Sorry. I saw you were merging and wanted to quickly submit. NO, that second line needs to be removed. It was my copy + paste temp store for the new URL . ;-)
will redo this one.

**Comment by TheBigBear** [comment]
sorry, will close this and redo

**Comment by TheBigBear** [comment]
@UtahDave new PR without that temp copy and paste buffer is https://github.com/saltstack/salt-winrepo/pull/231

**Comment by UtahDave** [comment]
Awesome. I'll take a look at that one.   By the way, if you make your fix to the same branch and push back to your Salt fork, that will update the pull request automatically. That way you don't have to create a whole new pull request.

**Comment by TheBigBear** [comment]
@UtahDave thanks for the tips, but I currently do these simple sls files entirely inside the github.com browser , I don't use git on the cmd line for this. But I have made a number of mistakes recently that I should probably learn from that and switch to using git on the cmd line. ;-)
That way I could have easily rebased the salt-minion ones yesterday.

**Comment by UtahDave** [comment]
Ah, ok. Well let me know if you need any help!

**Pull request closed without merging**
