### PR TITLE
Create initial postgresql.sls and postgresql_x86.sls

### PR DESCRIPTION
**Pull request by rrzaripov**
PostgreSQL: The world's most advanced open source database.

http://www.postgresql.org/

Tested on Windows 7 Professional x64, running salt-minion 2014.7.1

### CODE REVIEW

**Comment by TheBigBear** [comment]
@rrzaripov thanks for this. 

I do think the ```postgresql_x86 sls``` file is wrong. Since you have a 64-bit installer AND a 32-bit installer I am pretty sure the uninstaller for the 32-bit ```postgresql_x86``` version will also be under %ProgramFiles% and NOT under %ProgramFile(x86)%.

There is no "\Program Files (x86)\" folder on a 32-bit win os, which is what the ```*_x86.sls``` file is for.

Can you please double check, if you have access to a 32-bit client. 
Note: There is of course a %ProgramFiles(x86)% folder under a 64bit OS and IF you install the 32-bit version, that is indeed where the uninstaller would sit. Is that the scenario you were targeting?

But the winrepo sls ```*_x86.sls``` files are meant to be the ones for a 32bit install on a 32bit Win OS.

**Comment by rrzaripov** [comment]
@TheBigBear thank you for review and explanation.

I'll check the postgresql_x86.sls on 32-bit Windows, and then make update for this pull request.

**Comment by rrzaripov** [comment]
I tested sls files and will found, that `--prefix` and `--datadir` not work with `%ProgramFiles%`. Maybe this because `%ProgramFiles%` contains whitespace, in this case double quotes may solve problem.

On the other hand, if not use `--prefix` and `--datadir`, default paths is `%ProgramFiles%\PostgreSQL\9.x\`, so in update I'm omiting this options. 

Updated sls tested on Windows 7 Professional x86 and x64, Windows Server 2008 R2 x64.

**Comment by TheBigBear** [comment]
@rrzaripov thanks for this.

**Pull request merged**
