### PR TITLE
Update salt-minion.sls

### PR DESCRIPTION
**Pull request by b18**
Added releases 2014.7.2, 2014.7.4, and 2014.7.5

### CODE REVIEW

**Comment by rdoursenaud** [comment]
:+1:

**Comment by rdoursenaud** [comment]
salt-minion_x86.sls needs the same update

**Comment by cro** [comment]
@twangboy, @UtahDave should this be merged, or is it outdated now?

**Comment by UtahDave** [comment]
@b18 Hey, thanks so much for submitting this fix!  I apologize for not processing your pull request for so long. My backlog got crazy there for a while.

I merged a pull request recently that fixed the problem you were seeing, as I hadn't seen this pull request, so I'm going to close this pull request.  If you think this is still needed, please feel free to comment here and we'll reopen.

Thanks again!

**Comment by b18** [comment]
No problem! Thanks!

**Comment by twangboy** [comment]
@b18 Have you had luck using salt to upgrade itself using the winrepo?

**Pull request closed without merging**
