### PR TITLE
Create initial itunes.sls ver. 12.2.1.16

### PR DESCRIPTION
**Pull request by TheBigBear**
Created initial itunes.sls ver. 12.2.1.16

### CODE REVIEW

**Comment by UtahDave** [comment]
@TheBigBear thanks for all the updates!!

**Comment by TheBigBear** [comment]
@UtahDave, your welcome. ;-) 
What makes a difference is, that I have gone from merely testing on a developer machine to using ```live``` on a handful of machines and in the process have found many small inconsistencies in the way I had writtewn those winrepo pkgs that meant in the main the installer did not really recognise the pkgs as being installed and kept re-installing them every single time. 

The fault was most of the time that I did not have matching full description names between the pgk and the windows add/remove section, or differences in a version number being there (or not) in the windows add/remove programs section. So sorry, the past work was so "sloppy".

There is probably many more that I need to look over and re-test knowing what to look out for now.

Will do that in the coming days and weeks. Find it surprising that nobody picked me up on this. Granted they did install, but the logs never thought they completed correctly so it was installing them over and over again at every highstate call.

@UtahDave A shy question (and showing off my ignorance) from me, what are/is the criteria to be given write or commit access to the salt-winrepo? 
Now that I am in the swing of things and actually using it, waiting a few days for 'fixes' to be committed, seems a bit slow. Don't misunderstand me, I am NOT complaining, just wondering out loud if maybe I could actually be given commit access, if I'd asked. ;-)

**Comment by UtahDave** [comment]
@TheBigBear can you email me at dave@saltstack.com or google chat so we can discuss?

**Comment by TheBigBear** [comment]
Hi @UtahDave

On 14 Jul 2015, at 16:25, David Boucha <notifications@github.com<mailto:notifications@github.com>> wrote:

@TheBigBear<https://github.com/TheBigBear> can you email me at dave@saltstack.com<mailto:dave@saltstack.com> or google chat so we can discuss?

OK, here is an email. ;-)

I am off work in about 20 minutes, what time would work best for you for a quick chat?

I should be home in about 45 minutes (at UK BST 18:00) and could probably do most anytime in the three hours following that.

I opened up a google chat with you and will hopefully notice either an email response or google chat with a suggested time. Never in my life used google chat before, so hope it will all be intuitive. ;-)

Regards,

—

[cid:6CB3F12B-76D6-41EC-A856-A71D8E8640CA@uk.om.org]
________________________________
Operation Mobilisation (OM) - a company limited by guarantee - The Quinta, Weston Rhyn, Oswestry, SY10 7LT, United Kingdom
Company reg no: 2564320 (England & Wales) - Charity reg. no: 1008196 (England & Wales) - SC040988 (Scotland)
Web: http://www.uk.om.org

**Comment by UtahDave** [comment]
OK, ping me when you get home. I'll be available

**Pull request merged**
